spring:
  datasource:
     url: jdbc:mysql://localhost:3306/fly?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=true&amp;autoReconnect=true
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: root
     dbcp:
      time-between-eviction-runs-millis: 20000
      validation-query: 'SELECT 1'
      max-wait: 30000
      test-while-idle: true
      min-evictable-idle-time-millis: 28700
  jpa:
     show-sql: true
     hibernate.ddl-auto: update
     
  mail:
    host: smtp.sina.cn
    port: 25
    username: 123@sina.cn
    password: 123
    test-connection: true
  http:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true
    
logging:
  path: E:\project\log
  level:
    com.zhangxy: trace

server:
  port: 9000
  contextPath: /fly

security.sessions: if-required

